const TEAMS = [
  // --- ZONA ESTE (NL East) ---
  {
    id: "atlanta-braves",
    nombre: "Braves",
    apodo: "de Atlanta",
    ciudad: "Atlanta, Georgia",
    zona: "este",
    escudo: "../Images/Escudos/Atlanta_Braves.webp",
    color: "#CE1141",
    color2: "#13274F",
    fundacion: "1871",
    estadioId: "truist-park",
    descripcion: "Franquicia histórica perteneciente a la División Este de la Liga Nacional.",
    estadisticas: {
      victorias: 0, victoriasNota: "1ero",
      derrotas: 0,
      pctVictorias: ".000",
      sparkline: [1, 1, 1, 1, 1, 1],
      rachaTipo: "VICTORIAS", rachaCantidad: 1, ultimos10: "5-5",
    },
  },
  {
    id: "miami-marlins",
    nombre: "Marlins",
    apodo: "de Miami",
    ciudad: "Miami, Florida",
    zona: "este",
    escudo: "../Images/Escudos/miami-marlins-logo.webp",
    color: "#00A3E0",
    color2: "#EF3340",
    fundacion: "1993",
    estadioId: "loandepot-park",
    descripcion: "Equipo de la División Este de la Liga Nacional.",
    estadisticas: {
      victorias: 0, victoriasNota: "2do",
      derrotas: 0,
      pctVictorias: ".000",
      sparkline: [1, 0, 1, 0, 1, 0],
      rachaTipo: "VICTORIAS", rachaCantidad: 1, ultimos10: "5-5",
    },
  },
  {
    id: "new-york-mets",
    nombre: "Mets",
    apodo: "de Nueva York",
    ciudad: "Nueva York, Nueva York",
    zona: "este",
    escudo: "../Images/Escudos/NewYorkMets.webp",
    color: "#002D62",
    color2: "#FF5910",
    fundacion: "1962",
    estadioId: "citi-field",
    descripcion: "Equipo con sede en Queens perteneciente a la División Este.",
    estadisticas: {
      victorias: 0, victoriasNota: "3ero",
      derrotas: 0,
      pctVictorias: ".000",
      sparkline: [0, 1, 1, 0, 1, 0],
      rachaTipo: "DERROTAS", rachaCantidad: 1, ultimos10: "5-5",
    },
  },
  {
    id: "philadelphia-phillies",
    nombre: "Phillies",
    apodo: "de Filadelfia",
    ciudad: "Filadelfia, Pensilvania",
    zona: "este",
    escudo: "../Images/Escudos/Philladelphia_Phillips.webp",
    color: "#E71614",
    color2: "#284898",
    fundacion: "1883",
    estadioId: "citizens-bank-park",
    descripcion: "Uno de los equipos más antiguos de la División Este.",
    estadisticas: {
      victorias: 0, victoriasNota: "4to",
      derrotas: 0,
      pctVictorias: ".000",
      sparkline: [1, 0, 0, 1, 1, 0],
      rachaTipo: "VICTORIAS", rachaCantidad: 1, ultimos10: "5-5",
    },
  },
  {
    id: "washington-nationals",
    nombre: "Nationals",
    apodo: "de Washington",
    ciudad: "Washington, D.C.",
    zona: "este",
    escudo: "../Images/Escudos/Washington_Nationals.webp",
    color: "#AB0003",
    color2: "#14225A",
    fundacion: "1969",
    estadioId: "nationals-park",
    descripcion: "Equipo representante de la capital en la División Este.",
    estadisticas: {
      victorias: 0, victoriasNota: "5to",
      derrotas: 0,
      pctVictorias: ".000",
      sparkline: [0, 0, 1, 0, 1, 1],
      rachaTipo: "DERROTAS", rachaCantidad: 1, ultimos10: "5-5",
    },
  },

  // --- ZONA CENTRAL (NL Central) ---
  {
    id: "chicago-cubs",
    nombre: "Cubs",
    apodo: "de Chicago",
    ciudad: "Chicago, Illinois",
    zona: "central",
    escudo: "../Images/Escudos/Chicago_Cubs.webp",
    color: "#0E3386",
    color2: "#CC3433",
    fundacion: "1876",
    estadioId: "wrigley-field",
    descripcion: "Franquicia emblemática de la División Central de la Liga Nacional.",
    estadisticas: {
      victorias: 0, victoriasNota: "1ero",
      derrotas: 0,
      pctVictorias: ".000",
      sparkline: [1, 1, 0, 1, 0, 1],
      rachaTipo: "VICTORIAS", rachaCantidad: 1, ultimos10: "5-5",
    },
  },
  {
    id: "cincinnati-reds",
    nombre: "Reds",
    apodo: "de Cincinnati",
    ciudad: "Cincinnati, Ohio",
    zona: "central",
    escudo: "../Images/Escudos/Cincinnatti_reds.webp",
    color: "#C6011F",
    color2: "#000000",
    fundacion: "1881",
    estadioId: "great-american-ball-park",
    descripcion: "Equipo histórico del béisbol profesional en la División Central.",
    estadisticas: {
      victorias: 0, victoriasNota: "2do",
      derrotas: 0,
      pctVictorias: ".000",
      sparkline: [0, 1, 0, 1, 1, 0],
      rachaTipo: "DERROTAS", rachaCantidad: 1, ultimos10: "5-5",
    },
  },
  {
    id: "milwaukee-brewers",
    nombre: "Brewers",
    apodo: "de Milwaukee",
    ciudad: "Milwaukee, Wisconsin",
    zona: "central",
    escudo: "../Images/Escudos/Milwaukee Brewers.jpg",
    color: "#12284C",
    color2: "#FFC52F",
    fundacion: "1969",
    estadioId: "american-family-field",
    descripcion: "Competidor directo en la División Central de la Liga Nacional.",
    estadisticas: {
      victorias: 0, victoriasNota: "3ero",
      derrotas: 0,
      pctVictorias: ".000",
      sparkline: [1, 0, 1, 1, 0, 0],
      rachaTipo: "VICTORIAS", rachaCantidad: 1, ultimos10: "5-5",
    },
  },
  {
    id: "pittsburgh-pirates",
    nombre: "Pirates",
    apodo: "de Pittsburgh",
    ciudad: "Pittsburgh, Pensilvania",
    zona: "central",
    escudo: "../Images/Escudos/Pittsburgh Pirates.webp",
    color: "#FDB827",
    color2: "#000000",
    fundacion: "1881",
    estadioId: "pnc-park",
    descripcion: "Equipo con amplia tradición dentro de la División Central.",
    estadisticas: {
      victorias: 0, victoriasNota: "4to",
      derrotas: 0,
      pctVictorias: ".000",
      sparkline: [0, 0, 1, 0, 1, 0],
      rachaTipo: "DERROTAS", rachaCantidad: 1, ultimos10: "5-5",
    },
  },
  {
    id: "st-louis-cardinals",
    nombre: "Cardinals",
    apodo: "de San Luis",
    ciudad: "San Luis, Misuri",
    zona: "central",
    escudo: "../Images/Escudos/St. Louis Cardinals.webp",
    color: "#C41E3A",
    color2: "#0C2340",
    fundacion: "1882",
    estadioId: "busch-stadium",
    descripcion: "Una de las franquicias más ganadoras, perteneciente a la División Central.",
    estadisticas: {
      victorias: 0, victoriasNota: "5to",
      derrotas: 0,
      pctVictorias: ".000",
      sparkline: [1, 1, 0, 0, 1, 1],
      rachaTipo: "VICTORIAS", rachaCantidad: 1, ultimos10: "5-5",
    },
  },

  // --- ZONA OESTE (NL West) ---
  {
    id: "arizona-diamondbacks",
    nombre: "Diamondbacks",
    apodo: "de Arizona",
    ciudad: "Phoenix, Arizona",
    zona: "oeste",
    escudo: "../Images/Escudos/Arizona Diamondbacks.webp",
    color: "#A71930",
    color2: "#E3D4AD",
    fundacion: "1998",
    estadioId: "chase-field",
    descripcion: "Equipo representante del desierto en la División Oeste.",
    estadisticas: {
      victorias: 0, victoriasNota: "1ero",
      derrotas: 0,
      pctVictorias: ".000",
      sparkline: [1, 0, 1, 1, 0, 1],
      rachaTipo: "VICTORIAS", rachaCantidad: 1, ultimos10: "5-5",
    },
  },
  {
    id: "colorado-rockies",
    nombre: "Rockies",
    apodo: "de Colorado",
    ciudad: "Denver, Colorado",
    zona: "oeste",
    escudo: "../Images/Escudos/Colorado Rockies.webp",
    color: "#330066",
    color2: "#C4CED4",
    fundacion: "1993",
    estadioId: "coors-field",
    descripcion: "Equipo con sede en la ciudad de Denver en la División Oeste.",
    estadisticas: {
      victorias: 0, victoriasNota: "2do",
      derrotas: 0,
      pctVictorias: ".000",
      sparkline: [0, 1, 0, 0, 1, 0],
      rachaTipo: "DERROTAS", rachaCantidad: 1, ultimos10: "5-5",
    },
  },
  {
    id: "los-angeles-dodgers",
    nombre: "Dodgers",
    apodo: "de Los Ángeles",
    ciudad: "Los Ángeles, California",
    zona: "oeste",
    escudo: "../Images/Escudos/AngelesDodgers.webp",
    color: "#005A9C",
    color2: "#A5ACAF",
    fundacion: "1883",
    estadioId: "dodger-stadium",
    descripcion: "Franquicia emblemática de la División Oeste de la Liga Nacional.",
    estadisticas: {
      victorias: 0, victoriasNota: "3ero",
      derrotas: 0,
      pctVictorias: ".000",
      sparkline: [1, 1, 1, 0, 1, 1],
      rachaTipo: "VICTORIAS", rachaCantidad: 1, ultimos10: "5-5",
    },
  },
  {
    id: "san-diego-padres",
    nombre: "Padres",
    apodo: "de San Diego",
    ciudad: "San Diego, California",
    zona: "oeste",
    escudo: "../Images/Escudos/San Diego Padres.webp",
    color: "#2F241D",
    color2: "#FFC425",
    fundacion: "1969",
    estadioId: "petco-park",
    descripcion: "Equipo californiano perteneciente a la División Oeste.",
    estadisticas: {
      victorias: 0, victoriasNota: "4to",
      derrotas: 0,
      pctVictorias: ".000",
      sparkline: [0, 1, 1, 0, 0, 1],
      rachaTipo: "VICTORIAS", rachaCantidad: 1, ultimos10: "5-5",
    },
  },
  {
    id: "san-francisco-giants",
    nombre: "Giants",
    apodo: "de San Francisco",
    ciudad: "San Francisco, California",
    zona: "oeste",
    escudo: "../Images/Escudos/San Francisco Giants.webp",
    color: "#FD5A1E",
    color2: "#000000",
    fundacion: "1883",
    estadioId: "oracle-park",
    descripcion: "Histórico rival de la bahía en la División Oeste de la Liga Nacional.",
    estadisticas: {
      victorias: 0, victoriasNota: "5to",
      derrotas: 0,
      pctVictorias: ".000",
      sparkline: [1, 0, 0, 1, 0, 0],
      rachaTipo: "DERROTAS", rachaCantidad: 1, ultimos10: "5-5",
    },
  },
];

const STADIUMS = [
  {
    id: "estadio-monterrey",
    nombre: "Estadio de Beisbol Monterrey",
    equipoId: "sultanes",
    ciudad: "Monterrey, Nuevo León",
    capacidad: "27,398",
    inauguracion: "2019",
    color: "#1B2A5E",
    descripcion: "LoremIpsum",
    fotos: [
      { color: "#1B2A5E", caption: "Descripción de la foto" },
      { color: "#C9A227", caption: "Descripción de la foto" },
      { color: "#0a3d62", caption: "Descripción de la foto" },
    ],
  },
  {
    id: "estadio-cdmx",
    nombre: "Estadio Alfredo Harp Helú",
    equipoId: "diablos-rojos",
    ciudad: "Ciudad de México",
    capacidad: "20,000",
    inauguracion: "2019",
    color: "#C8102E",
    descripcion: "Texto de ejemplo: historia, características y datos curiosos del estadio. Sustituye este contenido por la información oficial cuando conectes la base de datos.",
    fotos: [
      { color: "#C8102E", caption: "Descripción de la foto" },
      { color: "#1A1A1A", caption: "Descripción de la foto" },
    ],
  },
  {
    id: "estadio-cancun",
    nombre: "Estadio Beto Ávila",
    equipoId: "tigres-qroo",
    ciudad: "Cancún, Quintana Roo",
    capacidad: "10,428",
    inauguracion: "1970",
    color: "#F58220",
    descripcion: "Texto de ejemplo: historia, características y datos curiosos del estadio. Sustituye este contenido por la información oficial cuando conectes la base de datos.",
    fotos: [
      { color: "#F58220", caption: "Descripción de la foto" },
      { color: "#1A1A1A", caption: "Descripción de la foto" },
    ],
  },
  {
    id: "estadio-guadalajara",
    nombre: "Estadio Panamericano",
    equipoId: "charros-jalisco",
    ciudad: "Guadalajara, Jalisco",
    capacidad: "18,000",
    inauguracion: "1992",
    color: "#7A1F2B",
    descripcion: "Texto de ejemplo: historia, características y datos curiosos del estadio. Sustituye este contenido por la información oficial cuando conectes la base de datos.",
    fotos: [
      { color: "#7A1F2B", caption: "Descripción de la foto" },
      { color: "#C9A227", caption: "Descripción de la foto" },
    ],
  },
  {
    id: "estadio-puebla",
    nombre: "Estadio Hermanos Serdán",
    equipoId: "pericos-puebla",
    ciudad: "Puebla, Puebla",
    capacidad: "12,000",
    inauguracion: "1972",
    color: "#2E7D32",
    descripcion: "Texto de ejemplo: historia, características y datos curiosos del estadio. Sustituye este contenido por la información oficial cuando conectes la base de datos.",
    fotos: [
      { color: "#2E7D32", caption: "Descripción de la foto" },
      { color: "#1A1A1A", caption: "Descripción de la foto" },
    ],
  },
  {
    id: "estadio-veracruz",
    nombre: "Estadio Beto Ávila (Veracruz)",
    equipoId: "aguilas-veracruz",
    ciudad: "Veracruz, Veracruz",
    capacidad: "12,500",
    inauguracion: "1973",
    color: "#B08D2B",
    descripcion: "Texto de ejemplo: historia, características y datos curiosos del estadio. Sustituye este contenido por la información oficial cuando conectes la base de datos.",
    fotos: [
      { color: "#B08D2B", caption: "Descripción de la foto" },
      { color: "#1A1A1A", caption: "Descripción de la foto" },
    ],
  },
  {
    id: "estadio-saltillo",
    nombre: "Estadio Francisco I. Madero",
    equipoId: "saraperos-saltillo",
    ciudad: "Saltillo, Coahuila",
    capacidad: "9,000",
    inauguracion: "1970",
    color: "#5B2A86",
    descripcion: "Texto de ejemplo: historia, características y datos curiosos del estadio. Sustituye este contenido por la información oficial cuando conectes la base de datos.",
    fotos: [
      { color: "#5B2A86", caption: "Descripción de la foto" },
      { color: "#C9A227", caption: "Descripción de la foto" },
    ],
  },
  {
    id: "estadio-aguascalientes",
    nombre: "Estadio Alberto Romo Chávez",
    equipoId: "rieleros-aguascalientes",
    ciudad: "Aguascalientes, Aguascalientes",
    capacidad: "10,500",
    inauguracion: "1973",
    color: "#0D6EFD",
    descripcion: "Texto de ejemplo: historia, características y datos curiosos del estadio. Sustituye este contenido por la información oficial cuando conectes la base de datos.",
    fotos: [
      { color: "#0D6EFD", caption: "Descripción de la foto" },
      { color: "#1A1A1A", caption: "Descripción de la foto" },
    ],
  },
];

/* Trivia: Liga Nacional de Béisbol (MLB, Estados Unidos).
   Reemplaza el arreglo TRIVIA completo de js/data.js por este.
   respuesta: true = Verdadero (derecha), false = Falso (izquierda). */
const TRIVIA = [
  {
    id: 1,
    pregunta: "Los Dodgers de Los Ángeles pertenecen a la Liga Nacional.",
    respuesta: true,
  },
  {
    id: 2,
    pregunta: "Los Yankees de Nueva York juegan en la Liga Nacional.",
    respuesta: false,
  },
  {
    id: 3,
    pregunta: "La Liga Nacional se fundó en 1876.",
    respuesta: true,
  },
  {
    id: 4,
    pregunta: "El Wrigley Field es la casa de los Cachorros de Chicago.",
    respuesta: true,
  },
  {
    id: 5,
    pregunta: "Los Medias Rojas de Boston forman parte de la Liga Nacional.",
    respuesta: false,
  },
  {
    id: 6,
    pregunta: "Los Dodgers jugaron en Brooklyn antes de mudarse a Los Ángeles.",
    respuesta: true,
  },
  {
    id: 7,
    pregunta: "Los Mets de Nueva York pertenecen a la Liga Americana.",
    respuesta: false,
  },
  {
    id: 8,
    pregunta: "Los Cardenales de San Luis son un equipo de la Liga Nacional.",
    respuesta: true,
  },
  {
    id: 9,
    pregunta: "Los Gigantes de San Francisco juegan en el Dodger Stadium.",
    respuesta: false,
  },
  {
    id: 10,
    pregunta: "Fernando Valenzuela ganó el Novato del Año y el Cy Young en 1981 con los Dodgers.",
    respuesta: true,
  },
];
